player:
########################################################################################################################
##                                                   Wiadomosci do ustawienia                                         ##
########################################################################################################################
cmdpomocx1: "&8----------[ &9POMOC &8]----------"
cmdpomocx2: " &7* &8/&9vip &8- &7informacje o randze vip"
cmdpomocx3: " &7* &8/&9svip &8- &7informacje o randze svip"
