player:
########################################################################################################################
##                                                   Wiadomosci do ustawienia                                         ##
########################################################################################################################
messages: "JD KURWE"
